#ifndef GUARD_CONSTANTS_WILD_ENCOUNTER_H
#define GUARD_CONSTANTS_WILD_ENCOUNTER_H

#define LAND_WILD_COUNT     4
#define WATER_WILD_COUNT    4
#define ROCK_WILD_COUNT     4
#define FISH_WILD_COUNT     8

#define NUM_ALTERING_CAVE_TABLES 9

#endif // GUARD_CONSTANTS_WILD_ENCOUNTER_H
